name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: pytestmate-continuous-integration
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install pytestmate
        run: uv sync --all-extras --dev

      - name: Run Pytest
        run: uv run pytest -v
